### ISSUE TITLE
Fresh install issue

### ISSUE THREAD

**Issue by MourIdri** [YunoHost-Apps/letsencrypt_ynh#5]
I jsut started my install and gt this : 

demo@mouradcloud:~$ yunohost domain cert-install
Error: yunohost command must be run as root or with sudo.
demo@mouradcloud:~$ su
Password:
root@mouradcloud:/home/demo# yunohost domain cert-install
Error: Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
  "status": 400
}
Error: Certificate installation for mouradcloud.westeurope.cloudapp.azure.com failed !
Exception: [Errno 22] Signing the new certificate failed

**Comment by MourIdri** [comment]
It seems the install script has to be updated... were is it located ?

**Comment by alexAubin** [comment]
This app (letsencrypt_ynh) is obsolete since Let's Encrypt support is directly integrated in Yunohost's core. You should refer to the documentation and the forum for questions regarding Let's Encrypt.

For your specific issue, see : https://forum.yunohost.org/t/en-fr-workaround-for-the-subscriber-agreement-update-or-lets-encrypt-contournement-pour-la-recente-mis-a-jour-des-conditions-dutilisation-de-lets-encrypt/3823

(Closing this, sorry)

**Comment by MourIdri** [comment]
Salut my French copain. I posted my workaround in your forum .

nano /usr/lib/moulinette/yunohost/vendor/acme_tiny/acme_tiny.py
and replace the line :
"https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"
with this one :
"https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
Then go back and do :
yunohost domain cert-install
